language: ruby
sudo: false
rvm:
  - 2.2.4
# before_script:
#   - export TZ=America/New_York
#   - psql -c 'create database ddmodels2_test;' -U postgres
#   - bundle exec rake db:create db:structure:load db:migrate
#   - cd /home/travis/build/MAPC/developmentdatabase/searchapp
#   - npm install
# script:
#   - bundle exec rake test
# cache: bundler
addons:
  postgresql: '9.3'
  code_climate:
    repo_token: 33b1d87b4e10a391447db6efa97c6f385d5f3f176c6a4d4dee124439e4ea7b12
    # ebd431336a17c38b101c377f4300158ce02a4a6588502935120f25eb162a4d70
